name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: ieqasample-dev  # Static Web App の名前
  AZURE_RESOURCE_GROUP: dev-iechatgpt  # リソースグループ名
  ENV: Production # デプロイ先
  DEPLOY_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: pnpm/action-setup@v2
        with:
          version: 7.26.0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
      - name: 'Setup: Install Dependencies'
        run: pnpm i --frozen-lockfile
      - name: 'Run Build'
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
          NEXT_PUBLIC_AZURE_TENANT_ID: ${{ secrets.NEXT_PUBLIC_AZURE_TENANT_ID }}
          NEXT_PUBLIC_AZURE_APP_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_AZURE_APP_CLIENT_ID }}
          NEXT_PUBLIC_AZURE_AUTHORITY: ${{ secrets.NEXT_PUBLIC_AZURE_AUTHORITY }}
          NEXT_PUBLIC_AZURE_KNOWN_AUTHORITY: ${{ secrets.NEXT_PUBLIC_AZURE_KNOWN_AUTHORITY }}
          NEXT_PUBLIC_AZURE_API_SCOPE: ${{ secrets.NEXT_PUBLIC_AZURE_API_SCOPE }}
        run: pnpm build
      # Azure CLI をセットアップ
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Azure Static Web Apps CLI をインストール
      - name: Install Azure Static Web Apps CLI
        run: npm install -g @azure/static-web-apps-cli
      # gnome-keyringをインストール
      - name: Install gnome-keyring
        run: sudo apt-get install -y gnome-keyring
      # swa deploy コマンドを実行
      - name: Deploy to Azure Static Web Apps
        run: swa deploy ./out --env $ENV -n $AZURE_WEBAPP_NAME -R $AZURE_RESOURCE_GROUP --deployment-token $DEPLOY_TOKEN

# https://learn.microsoft.com/ja-jp/azure/static-web-apps/build-configuration?tabs=github-actions#build-and-deploy